GET http://localhost:3003/api/blogs HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGx0ZXIiLCJpZCI6IjY0YzI2MDJjNjZhYmY5Y2JkNmY3NTE0MiIsImlhdCI6MTY5MTMzMDA5NiwiZXhwIjoxNjkxMzMzNjk2fQ.4rIw0kKvCIt5q1OiZ-rKwr6n3O15tKyWcqIObhnmlww

###

GET http://localhost:3003/api/blogs/?id= HTTP/1.1

###

GET http://localhost:3003/api/blogs/init-blogs/2 HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGx0ZXIiLCJpZCI6IjY0YzI2MDJjNjZhYmY5Y2JkNmY3NTE0MiIsImlhdCI6MTY5MTMzMDA5NiwiZXhwIjoxNjkxMzMzNjk2fQ.4rIw0kKvCIt5q1OiZ-rKwr6n3O15tKyWcqIObhnmlww

###

POST http://localhost:3003/api/blogs HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json

{
    "title": "I wanna be your lover30",
    "author": "Prince",
    "url": "3r.cx",
    "likes": 14
}

###

PUT http://localhost:3003/api/blogs/?id= HTTP/1.1
User-Agent: rest-client
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6,zh-CN;q=0.4
content-type: application/json

{
    "title": "I wanna be your lover",
    "author": "Prince",
    "url": "3r.cx",
    "likes": 14
}

###

DELETE http://localhost:3003/api/blogs/all-blogs HTTP/1.1

###

POST http://localhost:3003/api/blogs HTTP/1.1
User-Agent: rest-client
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGx0ZXIiLCJpZCI6IjY0NzQxNTE1YWU3NzBkZDk0ZWE3ZWYzYiIsImlhdCI6MTY4NTM0Nzg5OSwiZXhwIjoxNjg1MzUxNDk5fQ.apLNeXpQgLvFor7DPbGT0A-trqB9vlz2Q1xw9g8t6Vo

{
    "title": "Heros",
    "author": "David Bowie",
    "url": "urube",
    "likes": 256

}


